pipeline {
  agent any
  tools {
    nodejs 'nodejs12_16'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
    stage('Run job') {
      steps {
        build wait: false, job: 'tercer_job_con_parametro', parameters: 	[string(name: 'root_id', value: '$BUILD_ID')]
      }
    }
  }
}
